Number of changes to resolve linting problems (#2206)

diff --git a/.github/workflows/_tests-miscellaneous.yml b/.github/workflows/_tests-miscellaneous.yml
--- a/.github/workflows/_tests-miscellaneous.yml
+++ b/.github/workflows/_tests-miscellaneous.yml
@@ -45,16 +45,14 @@ jobs:
       - name: run linting on all our Dockerfiles
         id: hadolint
         run: |
-          find . -type f -name "*Dockerfile*" -exec sh -c 'for file; \
-          do echo "Processing $file"; \
-          docker run --rm -i -v ./hadolint.yaml:/.config/hadolint.yaml \
-          hadolint/hadolint < "$file"; \
-          done' sh {} +
-
-          if [ $? -ne 0 ]; then
-              echo "==== Dockerfile Linting Failure. Errors found ===="
-              exit 1
-          else
-              echo "==== Dockerfile Linting Success. No errors ===="
-              exit 0
-          fi
+          set -e
+          find . -type f -name "*Dockerfile*" -exec sh -c '
+            for file; do
+              echo "Processing $file"
+              if ! docker run --rm -i -v ./hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < "$file"; then
+                echo "==== Dockerfile Linting Failure. Errors found in $file ===="
+                exit 1
+              fi
+            done
+          ' sh {} +
+          echo "==== Dockerfile Linting Success. No errors ===="
