DDLS-626 fix end workflow

diff --git a/.github/workflows/workflow-pull-request-path.yml b/.github/workflows/workflow-pull-request-path.yml
--- a/.github/workflows/workflow-pull-request-path.yml
+++ b/.github/workflows/workflow-pull-request-path.yml
@@ -385,8 +385,8 @@ jobs:
       account_id: 248804316466
       workspace: ${{ needs.workflow_variables.outputs.build_identifier }}
 
-  end_of_workflow:
-    name: end of workflow
+  workflow_summary:
+    name: workflow summary
     runs-on: ubuntu-latest
     needs:
       - scale_services_down
@@ -394,13 +394,7 @@ jobs:
       - workflow_variables
     if: ${{ always() }}
     steps:
-      - name: Check workflow result
-        if: ${{ failure() }}
-        run: |
-          echo "A job failed. Marking end-workflow as failed."
-          exit 1
-      - name: workflow ended successfully
-        if: ${{ success() }}
+      - name: output workflow variables
         run: |
           export PUBLIC_FRONTEND_URL="https://${{ needs.workflow_variables.outputs.build_identifier }}.complete-deputy-report.service.gov.uk"
           export SERVICE_FRONTEND_URL="https://${{ needs.workflow_variables.outputs.build_identifier }}.digideps.opg.service.justice.gov.uk"
@@ -418,13 +412,18 @@ jobs:
           echo "- Service Frontend URL: ${SERVICE_FRONTEND_URL}" >> $GITHUB_STEP_SUMMARY
           echo "- Service Admin URL: ${SERVICE_ADMIN_URL}" >> $GITHUB_STEP_SUMMARY
           echo "- Tag Used: ${{ needs.workflow_variables.outputs.version_tag }}" >> $GITHUB_STEP_SUMMARY
+      - name: check for failure
+        if: ${{ failure() }}
+        run: |
+          echo "A job failed. Marking workflow_summary as failed."
+          exit 1
 
   slack_notify_success:
     name: notify of success
     uses: ./.github/workflows/_slack-notification.yml
     needs:
       - workflow_variables
-      - end_of_workflow
+      - workflow_summary
     with:
       success: yes
       branch: ${{ needs.workflow_variables.outputs.build_identifier }}
@@ -436,8 +435,17 @@ jobs:
     if: ${{ failure() }}
     needs:
       - workflow_variables
-      - end_of_workflow
+      - workflow_summary
     with:
       success: no
       branch: ${{ needs.workflow_variables.outputs.build_identifier }}
       account: 248804316466
+
+  end_of_workflow:
+    name: end of workflow
+    runs-on: ubuntu-latest
+    needs:
+      - slack_notify_success
+    steps:
+      - name: Mark workflow as successful
+        run: echo "workflow ended successfully"
